eLMS-SWE-main/eLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views
from froala_editor import views as froala_views


admin.site.site_header = "eLMS Administration"
admin.site.site_title = "eLMS Administration Portal"
admin.site.index_title = "Welcome to eLMS Administration Portal"


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('student/', views.guestStudent, name='guestStudent'),
    path('teacher/', views.guestFaculty, name='guestFaculty'),
    path('', include('main.urls')),
    path('', include('discussion.urls')),
    path('', include('attendance.urls')),
    path('', include('quiz.urls')),
    path('froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eLMS-SWE-main/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.myCourses, name='myCourses'),
    path('facultyCourses/', views.facultyCourses, name='facultyCourses'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.course_page, name='course'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('facultyProfile/<str:id>/', views.profile, name='profile_faculty'),
    path('faculty/<int:code>/', views.course_page_faculty, name='faculty'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<int:code>/', views.addAssignment, name='addAssignment'),
    path('assignment/<int:code>/<int:id>/',
         views.assignmentPage, name='assignmentPage'),
    path('assignments/<int:code>/', views.allAssignments, name='allAssignments'),
    path('student-assignments/<int:code>/',
         views.allAssignmentsSTD, name='student-assignments'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('course-material/<int:code>/',
         views.addCourseMaterial, name='addCourseMaterial'),
    path('course-material/<int:code>/<int:id>/',
         views.deleteCourseMaterial, name='deleteCourseMaterial'),
    path('courses/', views.courses, name='courses'),
    path('departments/', views.departments, name='departments'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordFaculty/', views.changePasswordFaculty,
         name='changePasswordFaculty'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoFaculty/', views.changePhotoFaculty,
         name='changePhotoFaculty'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
]

eLMS-SWE-main/main/models.py
from django.db import models
from froala_editor.fields import FroalaField
# Create your models here.


class Student(models.Model):
    student_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    role = models.CharField(
        default="Student", max_length=100, null=False, blank=True)
    course = models.ManyToManyField(
        'Course', related_name='students', blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_student.png')
    department = models.ForeignKey(
        'Department', on_delete=models.CASCADE, null=False, blank=False, related_name='students')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_student.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Students'

    def __str__(self):
        return self.name


class Faculty(models.Model):
    faculty_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    department = models.ForeignKey(
        'Department', on_delete=models.CASCADE, null=False, related_name='faculty')
    role = models.CharField(
        default="Faculty", max_length=100, null=False, blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_faculty.png')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_faculty.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Faculty'

    def __str__(self):
        return self.name


class Department(models.Model):
    department_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Departments'

    def __str__(self):
        return self.name

    def student_count(self):
        return self.students.count()

    def faculty_count(self):
        return self.faculty.count()

    def course_count(self):
        return self.courses.count()


class Course(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, null=False, unique=True)
    department = models.ForeignKey(
        Department, on_delete=models.CASCADE, null=False, related_name='courses')
    faculty = models.ForeignKey(
        Faculty, on_delete=models.SET_NULL, null=True, blank=True)
    studentKey = models.IntegerField(null=False, unique=True)
    facultyKey = models.IntegerField(null=False, unique=True)

    class Meta:
        unique_together = ('code', 'department', 'name')
        verbose_name_plural = "Courses"

    def __str__(self):
        return self.name


class Announcement(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    description = FroalaField()

    class Meta:
        verbose_name_plural = "Announcements"
        ordering = ['-datetime']

    def __str__(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")


class Assignment(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    deadline = models.DateTimeField(null=False)
    file = models.FileField(upload_to='assignments/', null=True, blank=True)
    marks = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    class Meta:
        verbose_name_plural = "Assignments"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def due_date(self):
        return self.deadline.strftime("%d-%b-%y, %I:%M %p")


class Submission(models.Model):
    assignment = models.ForeignKey(
        Assignment, on_delete=models.CASCADE, null=False)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)
    file = models.FileField(upload_to='submissions/', null=True,)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    marks = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=100, null=True, blank=True)

    def file_name(self):
        return self.file.name.split('/')[-1]

    def time_difference(self):
        difference = self.assignment.deadline - self.datetime
        days = difference.days
        hours = difference.seconds//3600
        minutes = (difference.seconds//60) % 60
        seconds = difference.seconds % 60

        if days == 0:
            if hours == 0:
                if minutes == 0:
                    return str(seconds) + " seconds"
                else:
                    return str(minutes) + " minutes " + str(seconds) + " seconds"
            else:
                return str(hours) + " hours " + str(minutes) + " minutes " + str(seconds) + " seconds"
        else:
            return str(days) + " days " + str(hours) + " hours " + str(minutes) + " minutes " + str(seconds) + " seconds"

    def submission_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.student.name + " - " + self.assignment.title

    class Meta:
        unique_together = ('assignment', 'student')
        verbose_name_plural = "Submissions"
        ordering = ['datetime']


class Material(models.Model):
    course_code = models.ForeignKey(
        Course, on_delete=models.CASCADE, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    file = models.FileField(upload_to='materials/', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Materials"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

eLMS-SWE-main/main/forms.py
from django import forms
from froala_editor.widgets import FroalaEditor
from .models import Announcement, Assignment, Material


class AnnouncementForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnnouncementForm, self).__init__(*args, **kwargs)
        self.fields['description'].required = True
        self.fields['description'].label = ''

    class Meta:
        model = Announcement
        fields = ['description']
        widgets = {
            'description': FroalaEditor(),
        }


class AssignmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AssignmentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True
            field.label = ''
        self.fields['file'].required = False

    class Meta:
        model = Assignment
        fields = ('title', 'description', 'deadline', 'marks', 'file')
        widgets = {
            'description': FroalaEditor(),
            'title': forms.TextInput(attrs={'class': 'form-control mt-1', 'id': 'title', 'name': 'title', 'placeholder': 'Title'}),
            'deadline': forms.DateTimeInput(attrs={'class': 'form-control mt-1', 'id': 'deadline', 'name': 'deadline', 'type': 'datetime-local'}),
            'marks': forms.NumberInput(attrs={'class': 'form-control mt-1', 'id': 'marks', 'name': 'marks', 'placeholder': 'Marks'}),
            'file': forms.FileInput(attrs={'class': 'form-control mt-1', 'id': 'file', 'name': 'file', 'aria-describedby': 'file', 'aria-label': 'Upload'}),
        }


class MaterialForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MaterialForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True
            field.label = ""
        self.fields['file'].required = False

    class Meta:
        model = Material
        fields = ('description', 'file')
        widgets = {
            'description': FroalaEditor(),
            'file': forms.FileInput(attrs={'class': 'form-control', 'id': 'file', 'name': 'file', 'aria-describedby': 'file', 'aria-label': 'Upload'}),
        }

eLMS-SWE-main/main/templates/main/access.html
{% extends 'index.html' %}
{% block title %} {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' student.student_id %}
{% endblock %}
{% block user %}
{{student.name}}
{% endblock user %}
{% block allCourses %}
{% url 'courses' %}
{% endblock%}
{% block courses %}
{% url 'myCourses' %}
{% endblock %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
   <span class="fw-bold"> {{ message }}</span>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}


<div class="container-fluid d-flex" style="min-height: 70vh;">
   <div class="row justify-content-center m-3 align-self-center w-100">
      <div class="col-lg-4 col-sm-12 col-md-6 border p-3 rounded">
         <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
               <label for="key" class="form-label">Enter the access key: </label>
               <input type="number" class="form-control" id="key" name="key" min="0" placeholder="e.g. 1234">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
         </form>
      </div>
   </div>
</div>
{% endblock %}

eLMS-SWE-main/main/templates/main/all-assignments.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Assignments | {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' faculty.faculty_id %}
{% endblock %}
{% block user %}
{{faculty.name}}
{% endblock user %}
{% block courses %}
{% url 'facultyCourses' %}
{% endblock courses %}
{% block allCourses %}
{% url 'courses' %}
{% endblock %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
               href="{% url 'facultyCourses' %}">My
               Courses</a>
            </li>
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
               href="{% url 'faculty' course.code %}">{{ course.name }}</a></li>
            <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">Assignment</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <!-- course name starts -->
      <div class="course-section p-3 m-3 shadow-sm d-flex justify-content-center">
         <div class="fw-bold fs-5 course_name">{{course.department}}-{{course.code}} : {{course.name}}</div>
      </div>
      <!-- course name ends -->
      <!-- assignment section starts -->
      <div class="course-section p-3 m-3 shadow">
         <div class="d-flex flex-row justify-content-between edit">
            <h4 class="fw-bold" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/open-book.png' %}"
               alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Assignment</h4>
            <a style="height:2rem"
               href="{% url 'addAssignment' course.code %}">
            <img src="{% static 'images/icon/iconBlack.png' %}"
               alt="" height="32">
            </a>
         </div>
         <hr>
         <div class="add-announcement">
            {% for assignment in assignments %}
            <!-- individual assignment starts --> 
            <a class="text-bold fs-6" href="{% url 'submission' course.code assignment.id %}">
            {{assignment.title}}</a>
            <div class="d-flex justify-content-between align-items-center">
               <p style="margin-bottom:0;" class="text-muted">Submitted : {{ assignment.submission_set.count}} / {{ studentCount }} </p>
               <p class="fs-6 text-muted" style="margin-bottom:0;">
                  {{assignment.due_date}}
               </p>
            </div>
            <p style="margin-bottom:0;">Submission ends : {{ assignment.due_date }}</p>
            <hr>
            <!-- individual assignment ends -->
            {% empty %}
            <h6 style="text-align:center">No assignments given yet</h6>
            {% endfor %}
         </div>
         <div class="text-center fs-6">
            <p>Showing {{ assignments.count}} of {{course.assignment_set.count}} {% if assignments.count == 1 %}assignment {% else %}assignments{% endif %}</p>
         </div>
      </div>
      <!-- assignment section ends -->
   </div>
</div>
{% endblock %}

eLMS-SWE-main/main/templates/main/announcement.html
{% extends 'index.html' %}
{% load static %}
{% block title %} {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' faculty.faculty_id %}
{% endblock %}
{% block user %}
{{faculty.name}}
{% endblock user %}
{% block allCourses %}
{% url 'courses' %}
{% endblock %}
{% block courses %}
{% url 'facultyCourses' %}
{% endblock courses %}
{% block content %}
<!-- navigation links -->
<div class="container shadow-sm">
   <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
      <ol class="breadcrumb p-3">
         <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'facultyCourses' %}">My
            courses</a>
         </li>
         <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)"
            href="{% url 'faculty' course.code %}">{{ course.name }}</a></li>
         <li class="breadcrumb-item active animate__animated animate__backInRight" aria-current="page">Announcement</li>
      </ol>
   </nav>
</div>
<!-- navigation links end -->
<div class="container">
   <div class="row justify-content-center">
      <div class="col-md-8 shadow-lg p-3 rounded">
         <div class="text-center">
            <div class="fw-bold mb-3 text-start">Post Announcement</div>
            <div class="from-group">
               <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <!-- submit button -->
                  <div class="d-flex justify-content-end bg-light border p-2 rounded">
                     <a class="btn btn-sm btn-outline-danger mx-2" href="{% url 'faculty' course.code %}">Cancel</a>
                     <button class="btn btn-sm btn-primary" type="submit" id="submit"> <span class="mx-2">Post</span></button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

eLMS-SWE-main/main/templates/main/course.html
{% extends 'index.html' %}
{% load static %}
{% block title %} {{ course.name }} | eLMS {% endblock title %}
{% block profile %}
{% url 'profile' student.student_id %}
{% endblock %}
{% block user %}
{{student.name}}
{% endblock user %}
{% block courses %}
{% url 'myCourses' %}
{% endblock courses %}
{% block allCourses %}
{% url 'courses' %}
{% endblock allCourses %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item fw-bold"><a style="color: rgb(10, 10, 48)" href="{% url 'myCourses' %}">My
               Courses</a>
            </li>
            <li class="breadcrumb-item fw-bold animate__animated animate__backInRight"><a class="breadcrumb-item active"
               aria-current="page">{{ course.name }}</a></li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <!-- course name starts -->
      <div class="rounded p-3 m-3 shadow d-flex justify-content-between">
         <span></span>
         <h5 class="mt-2 fw-bold">{{course.department}}-{{course.code}} : {{course.name}}</h5>
         <div class="dropdown">
            <img class="dropdown-toggle" id="drop" data-bs-toggle="dropdown" aria-expanded="false" src="{% static 'images/icon/dropDown.png' %}"
               alt="Options" height="32">
            <ul class="dropdown-menu">
               <li class="border-bottom">
                  <a class="dropdown-item" href="{% url 'discussion' course.code %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-right-dots mx-2" viewBox="0 0 16 16">
                        <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                        <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                     </svg>
                     Discussion
                  </a>
               </li>
               <li>
                  <a class="dropdown-item" href="{% url 'myQuizzes' course.code %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-text mx-2" viewBox="0 0 16 16">
                        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                        <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                     </svg>
                     Quiz
                  </a>
               </li>
            </ul>
         </div>
      </div>
      <!-- course name ends -->
      <!-- announcement section starts -->
      <div class="rounded p-3 m-3 shadow border border-top-0 border-end-0 border-bottom-0 border-primary border-5">
         <div class="fw-bold animate__animated animate__zoomInDown fs-5 text-center border-bottom border-1 mb-2 py-2" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/megaphone.png' %}"
            alt="" style="height:1.5rem;vertical-align: text-top"><span style="margin-right: 0.6rem;"></span>Announcement
         </div>
         <div>
            {% for announcement in announcements %}
            <!-- individual announcement starts -->
            <div class="fs-6" id="annDescription{{announcement.id}}">{% autoescape off %}{{announcement.description}}{% endautoescape %}</div>
            <div class="d-flex flex-row-reverse border-bottom border-1">
               <div style="color:grey;" class="mb-1">
                  {{announcement.post_date}}
               </div>
            </div>
            <!-- individual announcement ends-->
            {% empty %}
            <p class="fs-6 text-center text-muted">No announcement has been posted</p>
            {% endfor %}
         </div>
      </div>
      <!-- announcement section ends -->
      <!-- assignment section starts -->
      <div class="rounded p-3 m-3 shadow border border-top-0 border-bottom-0 border-end-0 border-danger border-5 mb-2">
         <div class="fw-bold fs-5 text-center animate__animated animate__zoomInDown border-bottom border-1 mb-2 py-2" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/open-book.png' %}"
            alt="" style="height:1.5rem; vertical-align: text-top"><span style="margin-right: 0.6rem;"></span>Assignment</div>
         <div >
            {% for assignment in assignments %}
            <!-- individual assignment starts -->
            <a class="fw-bold"
               href="{% url 'assignmentPage' course.code assignment.id %}">{{assignment.title}}</a>
            <div class="d-flex justify-content-between">
               <p style="font-size:15px"> Due Date : {{ assignment.due_date}} </p>
               <div  style="color:grey;">
                  {{assignment.post_date}}
               </div>
            </div>
            <!-- individual assignment ends -->
            {% empty %}
            <p class="text-center text-muted fs-6">No assignments given yet</p>
            {% endfor %}
         </div>
         {% if assignments %}
         <div class="text-center fs-6 text-muted d-flex flex-column border-top border-1">
            <span class="mt-2">Showing {{ assignments.count}} of {{course.assignment_set.count}}
            {% if assignments.count == 1 %}assignment {% else %}assignments{% endif %}
            </span>
            <a class="fs-6" href=" {% url 'student-assignments' course.code %} ">Show all</a>
         </div>
         {% endif %}
      </div>
      <!-- assignment section ends -->
      <!-- course material section starts -->
      <div class="rounded p-3 m-3 shadow border border-top-0 border-bottom-0 border-warning border-end-0 border-5" id="material">
         <!-- section title -->
         <div class="fw-bold animate__animated animate__zoomInDown fs-5 text-center border-bottom border-1 mb-2 py-2" style="color: rgb(10, 10, 48);"><img src="{% static 'images/icon/folder.png' %}"
            alt="" style="height:1.5rem;vertical-align: text-top"><span style="margin-right: 0.6rem;"></span>Course Material</div>
         <!-- section title ends -->
         <div>
            {% for material in materials  %}
            <!-- individual material starts -->
            <p>{% autoescape off %}{{ material.description }}{% endautoescape %}</p>
            <div class="d-flex justify-content-between text-break">
               {% if material.file %}
               <a class="fw-bold" href="{{ material.file.url }}"><span style="color:#9400d3" id="materialName">File : {{material.file.name}}</span></a><br>
               {% endif %}
               <div class="text-muted">
                  {{material.post_date}}
               </div>
            </div>
            {% empty %}
            <p class="text-center text-muted fs-6">Course materials not available</p>
            {% endfor %}
            <!-- individual material ends -->
         </div>
      </div>
      <!-- course material section ends -->
   </div>
</div>
<script>
   var materialName = document.getElementById("materialName").innerHTML;
   var materialName = materialName.replace("materials/", "");
   document.getElementById("materialName").innerHTML = materialName;
</script>
{% endblock %}